### ISSUE TITLE
doublon d'id

### ISSUE THREAD

**Issue by jdebray** [Ouest-France/cmp#71]
Après avoir passer notre site sur dareboost pour un controle de performance, nous constatons qu'il y a un doublon d'ID "scmp-description"
![image](https://user-images.githubusercontent.com/16759048/75663033-73f8d000-5c70-11ea-811f-1e4dd1811329.png)

Pour reproduire le bug, il suffit d'aller sur zoomcar.fr, d'ouvrir la console et rechercher "scmp-description" (cf screenshot)

**Comment by MatthieuPresse** [comment]
c'est corrigé normalment ! (pour info la sipacmp va bientôt être abandonnée si vous n'êtes pas au courant)
